name: dotlyn_core
description: Shared core logic for Dotlyn apps
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  vibration: ^3.1.4
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.1

dev_dependencies:
  test: ^1.24.0
  lints: ^4.0.0
