name: habit_tracker
description: "Habit Tracker app - Dotlyn Apps"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Packages partagÃ©s Dotlyn
  dotlyn_ui:
    path: ../../packages/dotlyn_ui
  dotlyn_core:
    path: ../../packages/dotlyn_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
